export const STORE_ANSWERS = 'STORE_ANSWERS';
export const GET_ANSWERS = 'GET_ANSWERS';
export const MARKED_QUESTIONS = 'MARKED_QUESTIONS';
export const SET_QUESTION_LENGTH = 'SET_QUESTION_LENGTH';
export const SET_ACTUAL_ANSWERS = 'SET_ACTUAL_ANSWERS';
export const UPDATE_QNO = 'UPDATE_QNO';
export const REGISTER_STUDENT = 'REGISTER_STUDENT';