export const data = [
    {
      personal: {
        name: 'John Doe',
        email: 'john.doe@example.com',
        cEmail: 'johndoe@gmail.com',
        mob: '1234567890',
        gender: 'Male',
        dob: '1990-01-01',
      },
      account: {
        creation_date: '2022-01-01',
        validation_date: '2022-01-02',
        isVerified: true,
      },
      ssc: {
        board: 'CBSE',
        year: 2006,
        percent: 85,
        location: 'Delhi',
      },
      hsc: {
        board: 'CBSE',
        stream: 'Science',
        year: 2008,
        percent: 90,
        location: 'Delhi',
      },
      ug: {
        university: 'Delhi University',
        year: 2012,
        prn: '123456',
        percent: 80,
        college: 'XYZ College',
        degree: 'B.Tech',
        branch: 'Computer Science',
      },
      pg: {
        university: 'Delhi University',
        year: 2014,
        prn: '123456',
        percent: 85,
        college: 'XYZ College',
        degree: 'M.Tech',
        branch: 'Computer Science',
      },
    },
    {
        personal: {
          name: 'Jane Doe',
          email: 'jane.doe@example.com',
          cEmail: 'janedoe@gmail.com',
          mob: '0987654321',
          gender: 'Female',
          dob: '1991-02-02',
        },
        account: {
          creation_date: '2022-02-02',
          validation_date: '2022-02-03',
          isVerified: true,
        },
        ssc: {
          board: 'ICSE',
          year: 2007,
          percent: 88,
          location: 'Mumbai',
        },
        hsc: {
          board: 'ICSE',
          stream: 'Commerce',
          year: 2009,
          percent: 92,
          location: 'Mumbai',
        },
        ug: {
          university: 'Mumbai University',
          year: 2013,
          prn: '654321',
          percent: 82,
          college: 'ABC College',
          degree: 'B.Com',
          branch: 'Finance',
        },
        pg: {
          university: 'Mumbai University',
          year: 2015,
          prn: '654321',
          percent: 87,
          college: 'ABC College',
          degree: 'M.Com',
          branch: 'Finance',
        },
      },
      {
  personal: {
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    cEmail: 'janedoe@gmail.com',
    mob: '0987654321',
    gender: 'Female',
    dob: '1991-02-02',
  },
  account: {
    creation_date: '2022-02-02',
    validation_date: '2022-02-03',
    isVerified: true,
  },
  ssc: {
    board: 'ICSE',
    year: 2007,
    percent: 88,
    location: 'Mumbai',
  },
  hsc: {
    board: 'ICSE',
    stream: 'Commerce',
    year: 2009,
    percent: 92,
    location: 'Mumbai',
  },
  ug: {
    university: 'Mumbai University',
    year: 2013,
    prn: '654321',
    percent: 82,
    college: 'ABC College',
    degree: 'B.Com',
    branch: 'Finance',
  },
  pg: {
    university: 'Mumbai University',
    year: 2015,
    prn: '654321',
    percent: 87,
    college: 'ABC College',
    degree: 'M.Com',
    branch: 'Finance',
  },
},
// Add 3 more similar objects for other students
{
    personal: {
        name: 'Alice Smith',
        email: 'alice.smith@example.com',
        cEmail: 'alicesmith@gmail.com',
        mob: '1122334455',
        gender: 'Female',
        dob: '1992-03-03',
    },
    account: {
        creation_date: '2022-03-03',
        validation_date: '2022-03-04',
        isVerified: true,
    },
    ssc: {
        board: 'State Board',
        year: 2008,
        percent: 89,
        location: 'Bangalore',
    },
    hsc: {
        board: 'State Board',
        stream: 'Arts',
        year: 2010,
        percent: 91,
        location: 'Bangalore',
    },
    ug: {
        university: 'Bangalore University',
        year: 2014,
        prn: '789012',
        percent: 83,
        college: 'DEF College',
        degree: 'BA',
        branch: 'English',
    },
    pg: {
        university: 'Bangalore University',
        year: 2016,
        prn: '789012',
        percent: 88,
        college: 'DEF College',
        degree: 'MA',
        branch: 'English',
    },
},
{
    personal: {
        name: 'Bob Johnson',
        email: 'bob.johnson@example.com',
        cEmail: 'bobjohnson@gmail.com',
        mob: '5566778899',
        gender: 'Male',
        dob: '1993-04-04',
    },
    account: {
        creation_date: '2022-04-04',
        validation_date: '2022-04-05',
        isVerified: true,
    },
    ssc: {
        board: 'CBSE',
        year: 2009,
        percent: 90,
        location: 'Chennai',
    },
    hsc: {
        board: 'CBSE',
        stream: 'Science',
        year: 2011,
        percent: 93,
        location: 'Chennai',
    },
    ug: {
        university: 'Chennai University',
        year: 2015,
        prn: '345678',
        percent: 84,
        college: 'GHI College',
        degree: 'B.Tech',
        branch: 'Mechanical Engineering',
    },
    pg: {
        university: 'Chennai University',
        year: 2017,
        prn: '345678',
        percent: 89,
        college: 'GHI College',
        degree: 'M.Tech',
        branch: 'Mechanical Engineering',
    },
},
{
    personal: {
        name: 'Charlie Brown',
        email: 'charlie.brown@example.com',
        cEmail: 'charliebrown@gmail.com',
        mob: '9988776655',
        gender: 'Male',
        dob: '1994-05-05',
    },
    account: {
        creation_date: '2022-05-05',
        validation_date: '2022-05-06',
        isVerified: true,
    },
    ssc: {
        board: 'ICSE',
        year: 2010,
        percent: 91,
        location: 'Kolkata',
    },
    hsc: {
        board: 'ICSE',
        stream: 'Commerce',
        year: 2012,
        percent: 94,
        location: 'Kolkata',
    },
    ug: {
        university: 'Kolkata University',
        year: 2016,
        prn: '901234',
        percent: 85,
        college: 'JKL College',
        degree: 'B.Com',
        branch: 'Accounting',
    },
    pg: {
        university: 'Kolkata University',
        year: 2018,
        prn: '901234',
        percent: 90,
        college: 'JKL College',
        degree: 'M.Com',
        branch: 'Accounting',
    },
},
  ];

